// 一副牌
const cards = {
	/*
		每副游戏牌共有108张卡牌，游戏牌分四种颜色：红色、绿色、蓝色及黄色
		每种颜色0牌有一张，1-9有两张
		每种颜色"skip"（跳牌）、"draw two"（罚牌2张）及"reverse"（反转出牌方向），每种各2张
		"wild"（转色）及"wild draw four"（转色及罚牌4张），每种各4张。
	*/
	normal: [
		// 红色
		{ color: 'red', symbol: '0' },
		{ color: 'red', symbol: '1' },
		{ color: 'red', symbol: '1' },
		{ color: 'red', symbol: '2' },
		{ color: 'red', symbol: '2' },
		{ color: 'red', symbol: '3' },
		{ color: 'red', symbol: '3' },
		{ color: 'red', symbol: '4' },
		{ color: 'red', symbol: '4' },
		{ color: 'red', symbol: '5' },
		{ color: 'red', symbol: '5' },
		{ color: 'red', symbol: '6' },
		{ color: 'red', symbol: '6' },
		{ color: 'red', symbol: '7' },
		{ color: 'red', symbol: '7' },
		{ color: 'red', symbol: '8' },
		{ color: 'red', symbol: '8' },
		{ color: 'red', symbol: '9' },
		{ color: 'red', symbol: '9' },
		{ color: 'red', symbol: 'S' },
		{ color: 'red', symbol: 'S' },
		{ color: 'red', symbol: 'D' },
		{ color: 'red', symbol: 'D' },
		{ color: 'red', symbol: 'R' },
		{ color: 'red', symbol: 'R' },
		
		// 黄色
		{ color: 'yellow', symbol: '0' },
		{ color: 'yellow', symbol: '1' },
		{ color: 'yellow', symbol: '1' },
		{ color: 'yellow', symbol: '2' },
		{ color: 'yellow', symbol: '2' },
		{ color: 'yellow', symbol: '3' },
		{ color: 'yellow', symbol: '3' },
		{ color: 'yellow', symbol: '4' },
		{ color: 'yellow', symbol: '4' },
		{ color: 'yellow', symbol: '5' },
		{ color: 'yellow', symbol: '5' },
		{ color: 'yellow', symbol: '6' },
		{ color: 'yellow', symbol: '6' },
		{ color: 'yellow', symbol: '7' },
		{ color: 'yellow', symbol: '7' },
		{ color: 'yellow', symbol: '8' },
		{ color: 'yellow', symbol: '8' },
		{ color: 'yellow', symbol: '9' },
		{ color: 'yellow', symbol: '9' },
		{ color: 'yellow', symbol: 'S' },
		{ color: 'yellow', symbol: 'S' },
		{ color: 'yellow', symbol: 'D' },
		{ color: 'yellow', symbol: 'D' },
		{ color: 'yellow', symbol: 'R' },
		{ color: 'yellow', symbol: 'R' },
		
		// 蓝色
		{ color: 'blue', symbol: '0' },
		{ color: 'blue', symbol: '1' },
		{ color: 'blue', symbol: '1' },
		{ color: 'blue', symbol: '2' },
		{ color: 'blue', symbol: '2' },
		{ color: 'blue', symbol: '3' },
		{ color: 'blue', symbol: '3' },
		{ color: 'blue', symbol: '4' },
		{ color: 'blue', symbol: '4' },
		{ color: 'blue', symbol: '5' },
		{ color: 'blue', symbol: '5' },
		{ color: 'blue', symbol: '6' },
		{ color: 'blue', symbol: '6' },
		{ color: 'blue', symbol: '7' },
		{ color: 'blue', symbol: '7' },
		{ color: 'blue', symbol: '8' },
		{ color: 'blue', symbol: '8' },
		{ color: 'blue', symbol: '9' },
		{ color: 'blue', symbol: '9' },
		{ color: 'blue', symbol: 'S' },
		{ color: 'blue', symbol: 'S' },
		{ color: 'blue', symbol: 'D' },
		{ color: 'blue', symbol: 'D' },
		{ color: 'blue', symbol: 'R' },
		{ color: 'blue', symbol: 'R' },
		
		// 绿色
		{ color: 'green', symbol: '0' },
		{ color: 'green', symbol: '1' },
		{ color: 'green', symbol: '1' },
		{ color: 'green', symbol: '2' },
		{ color: 'green', symbol: '2' },
		{ color: 'green', symbol: '3' },
		{ color: 'green', symbol: '3' },
		{ color: 'green', symbol: '4' },
		{ color: 'green', symbol: '4' },
		{ color: 'green', symbol: '5' },
		{ color: 'green', symbol: '5' },
		{ color: 'green', symbol: '6' },
		{ color: 'green', symbol: '6' },
		{ color: 'green', symbol: '7' },
		{ color: 'green', symbol: '7' },
		{ color: 'green', symbol: '8' },
		{ color: 'green', symbol: '8' },
		{ color: 'green', symbol: '9' },
		{ color: 'green', symbol: '9' },
		{ color: 'green', symbol: 'S' },
		{ color: 'green', symbol: 'S' },
		{ color: 'green', symbol: 'D' },
		{ color: 'green', symbol: 'D' },
		{ color: 'green', symbol: 'R' },
		{ color: 'green', symbol: 'R' },
		
		// 任意色 属性symbol中'W'为wild(转色)，'WD'为'wild draw'(转色及罚牌4张)
		{ color: 'any', symbol: 'W' },
		{ color: 'any', symbol: 'W' },
		{ color: 'any', symbol: 'W' },
		{ color: 'any', symbol: 'W' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
	],
	
	test: [
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'red', symbol: '0' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'any', symbol: 'WD' },
		{ color: 'green', symbol: '0' },
		{ color: 'green', symbol: '8' },
		{ color: 'green', symbol: '8' },
		{ color: 'green', symbol: '9' },
		{ color: 'green', symbol: '9' },
		{ color: 'red', symbol: '0' },
		{ color: 'red', symbol: '8' },
		{ color: 'red', symbol: '8' },
		{ color: 'red', symbol: '9' },
		{ color: 'red', symbol: '9' },
		{ color: 'yellow', symbol: '0' },
		{ color: 'yellow', symbol: '8' },
		{ color: 'yellow', symbol: '8' },
		{ color: 'yellow', symbol: '9' },
		{ color: 'yellow', symbol: '9' },
		{ color: 'blue', symbol: '0' },
		{ color: 'blue', symbol: '8' },
		{ color: 'blue', symbol: '8' },
		{ color: 'blue', symbol: '9' },
		{ color: 'blue', symbol: '9' },
	]
}

export default cards